### ISSUE TITLE
Custom tags for notes

### ISSUE THREAD

**Issue by mr-hogg** [xerosis/openResources#59]
In the notes, add the ability to do something like: [image: 45] to embed the correct credit etc.

**Comment by mr-hogg** [comment]
Also add the ability to link to resources, e.g. [resource:99]

**Comment by kieranhogg** [comment]
Embed.ly card: http://embed.ly/code?url=http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FAlternate_air_ticket_purchasing_order_system

**Comment by kieranhogg** [comment]
(resource)[<resource_code>] implemented, (image)[<image_code>] still to do.

**Comment by kieranhogg** [comment]
github's image tag for reference: ![ image ](<url>)
